spring.profiles.include=secret

spring.application.name=estruturaOrganizacional
server.port=8081

eureka.client.service-url.defaultZone=http://192.168.1.7:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.ucsizdretesteudlsaro 
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

